/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlydethi;

import CTDL.CauHoi;
import static CTDL.CauHoi.MULTI;
import static CTDL.CauHoi.YESNO;
import CTDL.CauHoiNhieuLC;
import CTDL.LuaChon;
import functions.Modify;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.table.DefaultTableModel;
import static quanlydethi.ShowFrame.cauHoiDangChon;
import static quanlydethi.ShowFrame.monDangChon;

/**
 *
 * @author HUYENKUTE
 */
public class TaoMoiCauHoiMulti extends javax.swing.JFrame {

    /**
     * Creates new form ModifyCauHoiYesNO
     */
    private CauHoiNhieuLC cauHoi = null;
    private int dem = 0;

    TaoMoiCauHoiMulti(String t) {
        initComponents();
        dem = 0;
        jTextField_MonHoc.setText(ShowFrame.monDangChon.getTenMH());
        cauHoi = new CauHoiNhieuLC() {
        };
        cauHoi.setNoiDung("");
        cauHoi.setLoai(MULTI);
        cauHoi.setMaMH(ShowFrame.monDangChon.getMaMH());
        cauHoi.setChuong(1);
        cauHoi.setTrinhDo("Cao Đẳng");
        
        
        jTextField_MonHoc.setEditable(false);
        jButtonXoaLC.setEnabled(false);
        jButtonDatLamDapAn.setEnabled(false);
        this.setTitle(t);
        jTextField_MonHoc.setEditable(false);
        jTextArea_NoiDungCauHoi.setText(cauHoi.getNoiDung());
        jButtonLuu_CSDL.setEnabled(false);
        
//        jLabel_DapAN.setText(cauHoi.getDapAn().getTenLC()+"");
        
        LoadDanhSachLuaChon();  
    }
    
    public void LoadDanhSachLuaChon()
    { 
        jTable_DsLuaChon.removeAll();
        DefaultTableModel model1 = new DefaultTableModel();

        model1.addColumn("Tên Lựa chọn");
        model1.addColumn("Nội Dung");

        Vector vec;
         // show map
        Iterator<Character> itr = cauHoi.danhsachLuaChon.keySet().iterator();
        while (itr.hasNext()) {
//            System.out.println(cauHoi.danhsachLuaChon.get(itr.next()));
            LuaChon tmp = cauHoi.danhsachLuaChon.get(itr.next());
            vec = new Vector();
            vec.add(tmp.getTenLC());
            vec.add(tmp.getNoiDungLC());
            model1.addRow(vec);
        }
        jTable_DsLuaChon.setModel(model1);
    }
   
    public TaoMoiCauHoiMulti() {
        initComponents();
        if(cauHoiDangChon instanceof CauHoiNhieuLC) cauHoi = ((CauHoiNhieuLC)cauHoiDangChon);
       
        jButtonXoaLC.setEnabled(false);
        jButtonDatLamDapAn.setEnabled(false);
        this.setTitle("XEM CHI TIẾT CÂU HỎI [" +cauHoiDangChon+ "]");
        jTextField_MonHoc.setEditable(false);
        jTextArea_NoiDungCauHoi.setText(cauHoiDangChon.getNoiDung());
        jButtonLuu_CSDL.setEnabled(false);
        
        jLabel_DapAN.setText(cauHoi.getDapAn().getTenLC()+"");
        
        LoadDanhSachLuaChon();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_MonHoc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel_ID_CauHoi2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_NoiDungCauHoi = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_DsLuaChon = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButtonXoaLC = new javax.swing.JButton();
        jButtonDatLamDapAn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel_DapAN = new javax.swing.JLabel();
        jPanel_NewLuaChon = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton_Them1NoiDungLuaChon = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_NoiDungLuaChon = new javax.swing.JTextArea();
        jTextField_Chuong1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_TrinhDo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButtonLuu_CSDL = new javax.swing.JButton();

        setTitle("Quản Lý Câu Hỏi");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(1300, 700));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 204))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 700));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));

        jLabel4.setBackground(new java.awt.Color(0, 51, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Môn học:");

        jTextField_MonHoc.setBackground(new java.awt.Color(204, 204, 255));
        jTextField_MonHoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_MonHoc.setForeground(new java.awt.Color(0, 0, 204));
        jTextField_MonHoc.setText("GV001");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_MonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_MonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Loại:");

        jLabel_ID_CauHoi2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_ID_CauHoi2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel_ID_CauHoi2.setText("CÂU HỎI NHIỀU LỰA CHỌN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_ID_CauHoi2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel_ID_CauHoi2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Xem Câu Hỏi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 255, 204), new java.awt.Color(204, 204, 0), new java.awt.Color(51, 102, 0), new java.awt.Color(51, 51, 0)));

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nội dung câu hỏi:");

        jTextArea_NoiDungCauHoi.setColumns(20);
        jTextArea_NoiDungCauHoi.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        jTextArea_NoiDungCauHoi.setForeground(new java.awt.Color(0, 0, 204));
        jTextArea_NoiDungCauHoi.setRows(5);
        jTextArea_NoiDungCauHoi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextArea_NoiDungCauHoiFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea_NoiDungCauHoi);

        jTable_DsLuaChon.setBackground(new java.awt.Color(255, 153, 153));
        jTable_DsLuaChon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable_DsLuaChon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_DsLuaChon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable_DsLuaChonFocusLost(evt);
            }
        });
        jTable_DsLuaChon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_DsLuaChonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_DsLuaChon);

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Danh sách lựa chọn:");

        jButtonXoaLC.setBackground(new java.awt.Color(255, 102, 0));
        jButtonXoaLC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonXoaLC.setText("XÓA LỰA CHỌN NÀY");
        jButtonXoaLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaLCActionPerformed(evt);
            }
        });

        jButtonDatLamDapAn.setBackground(new java.awt.Color(0, 153, 255));
        jButtonDatLamDapAn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDatLamDapAn.setText("ĐẶT LÀM ĐÁP ÁN");
        jButtonDatLamDapAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDatLamDapAnActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(0, 51, 51));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setText("Đấp án:");

        jLabel_DapAN.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_DapAN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_DapAN.setForeground(new java.awt.Color(0, 0, 204));
        jLabel_DapAN.setText("Chưa có");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(jButtonDatLamDapAn, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_DapAN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jButtonXoaLC, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_DapAN))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonDatLamDapAn)
                        .addComponent(jButtonXoaLC)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_NewLuaChon.setBackground(new java.awt.Color(0, 102, 102));
        jPanel_NewLuaChon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Điều Chỉnh", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel7.setBackground(new java.awt.Color(0, 51, 51));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Thêm 1 nội dung lựa chọn:");

        jButton_Them1NoiDungLuaChon.setBackground(new java.awt.Color(102, 204, 255));
        jButton_Them1NoiDungLuaChon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Them1NoiDungLuaChon.setText("THÊM ");
        jButton_Them1NoiDungLuaChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Them1NoiDungLuaChonActionPerformed(evt);
            }
        });

        jTextArea_NoiDungLuaChon.setColumns(20);
        jTextArea_NoiDungLuaChon.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jTextArea_NoiDungLuaChon.setRows(5);
        jTextArea_NoiDungLuaChon.setText("Nhập nội dung lựa chọn vào đây...");
        jTextArea_NoiDungLuaChon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextArea_NoiDungLuaChonFocusGained(evt);
            }
        });
        jTextArea_NoiDungLuaChon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea_NoiDungLuaChonMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTextArea_NoiDungLuaChon);

        jTextField_Chuong1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_Chuong1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_Chuong1.setForeground(new java.awt.Color(153, 0, 0));
        jTextField_Chuong1.setText("1");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Chương:");

        jComboBox_TrinhDo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_TrinhDo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CAO ĐẲNG", "ĐẠI HỌC", "VĂN BẰNG 2", " " }));
        jComboBox_TrinhDo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_TrinhDoItemStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Trình độ:");

        jButtonLuu_CSDL.setBackground(new java.awt.Color(0, 0, 102));
        jButtonLuu_CSDL.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonLuu_CSDL.setForeground(new java.awt.Color(102, 255, 102));
        jButtonLuu_CSDL.setText("LƯU THAY ĐỔI VÀO CSDL");
        jButtonLuu_CSDL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLuu_CSDLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_NewLuaChonLayout = new javax.swing.GroupLayout(jPanel_NewLuaChon);
        jPanel_NewLuaChon.setLayout(jPanel_NewLuaChonLayout);
        jPanel_NewLuaChonLayout.setHorizontalGroup(
            jPanel_NewLuaChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_NewLuaChonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_NewLuaChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_NewLuaChonLayout.createSequentialGroup()
                        .addGroup(jPanel_NewLuaChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel_NewLuaChonLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_NewLuaChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Chuong1)
                            .addComponent(jComboBox_TrinhDo, 0, 252, Short.MAX_VALUE)))
                    .addGroup(jPanel_NewLuaChonLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jButton_Them1NoiDungLuaChon, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_NewLuaChonLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonLuu_CSDL, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel_NewLuaChonLayout.setVerticalGroup(
            jPanel_NewLuaChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_NewLuaChonLayout.createSequentialGroup()
                .addGroup(jPanel_NewLuaChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Chuong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel_NewLuaChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox_TrinhDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel_NewLuaChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButton_Them1NoiDungLuaChon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLuu_CSDL)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_NewLuaChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_NewLuaChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1267, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Them1NoiDungLuaChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Them1NoiDungLuaChonActionPerformed
        // TODO add your handling code here:
        String res = jTextArea_NoiDungLuaChon.getText().toString().trim();
        
        if(res.isEmpty() || res.equals("Nhập nội dung lựa chọn vào đây..."))
        {
            JOptionPane.showMessageDialog(null,"Nội dung lựa chọn không được trống!!!", "Cảnh báo",WARNING_MESSAGE);
            jTextArea_NoiDungLuaChon.requestFocus();
            return;
        }
        else
        {
            char c = 'A';
            c+=dem++;
            cauHoi.danhsachLuaChon.put(c, new LuaChon(c, res));
            System.out.println("---> Lua chọn mơi them: " + c +"  : "+ cauHoi.danhsachLuaChon.get(c));
            LoadDanhSachLuaChon();
            jTextArea_NoiDungLuaChon.setText("Nhập nội dung lựa chọn vào đây...");
        }
        
    }//GEN-LAST:event_jButton_Them1NoiDungLuaChonActionPerformed

    private void jButtonDatLamDapAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDatLamDapAnActionPerformed
        // TODO add your handling code here:
        if(jTable_DsLuaChon.getSelectedRow() != -1)
        {
            cauHoi.thayDapAn(cauHoi.danhsachLuaChon.get(jTable_DsLuaChon.getValueAt(jTable_DsLuaChon.getSelectedRow(),0).toString().charAt(0)));
            jLabel_DapAN.setText(cauHoi.getDapAn().getTenLC()+"");
            if(cauHoi.getNoiDung().isEmpty())
                jButtonLuu_CSDL.setEnabled(true);
        }
        else
        {
            
            JOptionPane.showMessageDialog(null,"bạn chưa chọn Lựa Chọn nào!!!", "Thông báo",WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDatLamDapAnActionPerformed

    private void jTable_DsLuaChonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable_DsLuaChonFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_DsLuaChonFocusLost

    private void jTable_DsLuaChonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DsLuaChonMouseClicked
        // TODO add your handling code here:
        
        jButtonXoaLC.setEnabled(true);
        jButtonDatLamDapAn.setEnabled(true);
    }//GEN-LAST:event_jTable_DsLuaChonMouseClicked

    private void jComboBox_TrinhDoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_TrinhDoItemStateChanged
        // TODO add your handling code here:
        
        cauHoi.setTrinhDo(jComboBox_TrinhDo.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox_TrinhDoItemStateChanged

    private void jButtonLuu_CSDLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLuu_CSDLActionPerformed
        // TODO add your handling code here:
        if(cauHoi.getNoiDung().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Nội dung CÂU HỎI không được trống!!!", "Cảnh báo",WARNING_MESSAGE);
            jTextArea_NoiDungCauHoi.requestFocus();
            return;
        }
        if(cauHoi.danhsachLuaChon.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Danh sách LỰA CHỌN không được trống!!!", "Cảnh báo",WARNING_MESSAGE);
            jTextArea_NoiDungLuaChon.requestFocus();
            return;
        }
        if(cauHoi.dapAn == null)
        {
            JOptionPane.showMessageDialog(null,"BẠN CHƯA CHỌN ĐÁP ÁN!!!", "Cảnh báo",WARNING_MESSAGE);
            return;
        }
        if(Modify.ThemCauHoiVaoCSDL(cauHoi))
        {
            JOptionPane.showMessageDialog(null,"Thêm Câu hỏi vào CSDL thành công!", "Thông báo",INFORMATION_MESSAGE);
            this.setVisible(false);
            MainFrame.show.LoadCauHoiRaBang();
            return;
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Thêm Câu hỏi vào CSDL Thất bại!", "Thông báo",WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButtonLuu_CSDLActionPerformed

    private void jButtonXoaLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaLCActionPerformed
        // TODO add your handling code here:
        if(jTable_DsLuaChon.getSelectedRow() == -1)
        {
            JOptionPane.showMessageDialog(null,"bạn chưa chọn Lựa Chọn để xóa!!!", "Thông báo",WARNING_MESSAGE);
            return;
        }
        
        if(cauHoi.getDapAn().getTenLC()!=null && cauHoi.dapAn.getTenLC().equals(cauHoi.danhsachLuaChon.get(jTable_DsLuaChon.getValueAt(jTable_DsLuaChon.getSelectedRow(),1).toString().charAt(0))))
        {
            JOptionPane.showMessageDialog(null,"BẠN KHÔNG ĐƯỢC LOẠI BỎ ĐÁP ÁN!!!", "Cảnh báo",WARNING_MESSAGE);
            return;
        }
        if(cauHoi.danhsachLuaChon.size()>0)
        {
            cauHoi.danhsachLuaChon.remove(jTable_DsLuaChon.getValueAt(jTable_DsLuaChon.getSelectedRow(),0).toString().charAt(0));
            LoadDanhSachLuaChon();
        }
        if(cauHoi.danhsachLuaChon.isEmpty())
        {
            jButtonDatLamDapAn.setEnabled(false);
            cauHoi.thayDapAn(null);
            jLabel_DapAN.setText("Chưa có");
            return;
        }
        else{
            if(!cauHoi.getNoiDung().isEmpty())
                jButtonLuu_CSDL.setEnabled(true);   
            
        }
    }//GEN-LAST:event_jButtonXoaLCActionPerformed

    private void jTextArea_NoiDungLuaChonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea_NoiDungLuaChonFocusGained
        // TODO add your handling code here:
        if(jTextArea_NoiDungLuaChon.getText().toString().trim().equals("Nhập nội dung lựa chọn vào đây..."))
            jTextArea_NoiDungLuaChon.setText("");
        
    }//GEN-LAST:event_jTextArea_NoiDungLuaChonFocusGained

    private void jTextArea_NoiDungCauHoiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea_NoiDungCauHoiFocusLost
        // TODO add your handling code here:
        jButtonLuu_CSDL.setEnabled(true);
        String res = jTextArea_NoiDungCauHoi.getText().toString().trim();
        if(!res.isEmpty())
        {
            cauHoi.setNoiDung(res);
            
        }
        else
        {
             jButtonLuu_CSDL.setEnabled(false);
        }
            
    }//GEN-LAST:event_jTextArea_NoiDungCauHoiFocusLost

    private void jTextArea_NoiDungLuaChonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea_NoiDungLuaChonMouseClicked
        // TODO add your handling code here:
        if(jTextArea_NoiDungLuaChon.getText().toString().trim().equals("Nhập nội dung lựa chọn vào đây..."))
            jTextArea_NoiDungLuaChon.setText("");
        
    }//GEN-LAST:event_jTextArea_NoiDungLuaChonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaoMoiCauHoiMulti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaoMoiCauHoiMulti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaoMoiCauHoiMulti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaoMoiCauHoiMulti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaoMoiCauHoiMulti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDatLamDapAn;
    private javax.swing.JButton jButtonLuu_CSDL;
    private javax.swing.JButton jButtonXoaLC;
    private javax.swing.JButton jButton_Them1NoiDungLuaChon;
    private javax.swing.JComboBox<String> jComboBox_TrinhDo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_DapAN;
    private javax.swing.JLabel jLabel_ID_CauHoi2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_NewLuaChon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_DsLuaChon;
    private javax.swing.JTextArea jTextArea_NoiDungCauHoi;
    private javax.swing.JTextArea jTextArea_NoiDungLuaChon;
    private javax.swing.JTextField jTextField_Chuong1;
    private javax.swing.JTextField jTextField_MonHoc;
    // End of variables declaration//GEN-END:variables
}
