/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlydethi;
import CTDL.CauHoi;
import CTDL.CauHoiNhieuLC;
import CTDL.DeThi;
import CTDL.GiangDay;
import functions.DBConection;
import functions.Modify;
import functions.ThreadDH;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Random;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CVanHau
 */
public class ThiThu extends javax.swing.JFrame  {
    Thread dh;
    int n;
    private GiangDay giangDay;
    HashMap<Integer,Character> cautraloi;
    ArrayList<CauHoi> dsch; // tat ca cau hoi
    ArrayList<CauHoi> dsch1mon;
    Connection ketNoi = DBConection.layKetNoi();
    DefaultTableModel dtm;
    DeThi de = new DeThi();
    int maDe = 0;
    boolean stop = false;
   /**
     * Creates new form ThiThu
     */
    public ThiThu(GiangDay gd, ArrayList<CauHoi> ds) {
        initComponents();
        giangDay = gd;
        dsch = ds;
        dsch1mon = new ArrayList<>();
        loadLichThi();
        
    }
    void hienthicauhoi(CauHoi ch){
        jLabelCauHoi.setText("Câu "+ (n+1)+": "+ch.getNoiDung());
        jLabel_phanchon.setText(ch.hienthidapan());
        if(cautraloi.containsKey(n)) jTextField_cautraloi.setText(cautraloi.get(n).toString());
    }
    void thi(DeThi de) {
        dh = new Thread(new ThreadDH(jLabel_thoiGian,de.thoiGianThi, stop));
        dh.setPriority(Thread.MAX_PRIORITY);
        dh.start();
        cautraloi = new HashMap<Integer,Character>();
        cautraloi.clear();
        
        jLabel_maMon.setText(de.maMonHoc);
        jLabel_maLop.setText(de.maLop);
        jLabel_ngayThi.setText(de.ngayThi);
        jLabel_trinhDo.setText(de.trinhDo);
        n=0;
        
        hienthicauhoi(de.danhsachCauHoi.get(n));
        
        Thi.setVisible(true);
        
    }
    public void loadLichThi()  {
        
        try {
            dtm = (DefaultTableModel) jTable_LichThi.getModel();
            dtm.setNumRows(0);
//           /
            String sql = "SELECT * FROM XEPLICHTHI Where MAGV = '"+giangDay.giangvien.getMaGV()+"'";
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                Vector<Object> data = new Vector<>();
                data.add(rs.getString(1));
                data.add(rs.getString(2));
                data.add(rs.getString(3));
                data.add(rs.getString(4));
                data.add(rs.getString(5));
                data.add(rs.getString(6));
                data.add(rs.getString(7));
                data.add(rs.getString(8));
                dtm.addRow(data);
            }
            rs.close();
            ps.close();

        } catch (SQLException ex) {
            System.err.println("Loi LoadLichThi()");
        }
        
    }
    String kt_dapan(){
        int dem=0;
        for(int i = 0; i< de.soCau; i++){
            if(cautraloi.get(i)!= null)
                if(de.danhsachCauHoi.get(i).checkCauTraLoi(cautraloi.get(i))==true) dem++;
        }
        return "Số câu trả lời đúng: " + dem+"/"+de.soCau;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Thi = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel_maMon = new javax.swing.JLabel();
        jLabel_maLop = new javax.swing.JLabel();
        jLabel_ngayThi = new javax.swing.JLabel();
        jLabel_trinhDo = new javax.swing.JLabel();
        jLabel_thoiGian = new javax.swing.JLabel();
        jButton_CauTruoc = new javax.swing.JButton();
        jButton_CauSau = new javax.swing.JButton();
        jLabel_phanchon = new javax.swing.JLabel();
        jTextField_cautraloi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton_NopBai = new javax.swing.JButton();
        jLabelCauHoi = new javax.swing.JLabel();
        jButton_TaoDe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_LichThi = new javax.swing.JTable();

        Thi.setModal(true);
        Thi.setResizable(false);
        Thi.setSize(new java.awt.Dimension(600, 400));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("THI THỬ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Môn thi:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Lớp:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Trình độ:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Ngày thi:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Thời gian còn lại:");

        jLabel_maMon.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel_maMon.setText("mã môn");

        jLabel_maLop.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel_maLop.setText("mã lớp");

        jLabel_ngayThi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel_ngayThi.setText("ngày thi");

        jLabel_trinhDo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel_trinhDo.setText("trình độ");

        jLabel_thoiGian.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel_thoiGian.setText("00:00");

        jButton_CauTruoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton_CauTruoc.setText("Câu trước");
        jButton_CauTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CauTruocActionPerformed(evt);
            }
        });

        jButton_CauSau.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton_CauSau.setText("Câu sau");
        jButton_CauSau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CauSauActionPerformed(evt);
            }
        });

        jLabel_phanchon.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTextField_cautraloi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_cautraloiKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Nhập câu trả lời:");

        jButton_NopBai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton_NopBai.setText("Nộp bài");
        jButton_NopBai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NopBaiActionPerformed(evt);
            }
        });

        jLabelCauHoi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelCauHoi.setText("jLabel10");

        javax.swing.GroupLayout ThiLayout = new javax.swing.GroupLayout(Thi.getContentPane());
        Thi.getContentPane().setLayout(ThiLayout);
        ThiLayout.setHorizontalGroup(
            ThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThiLayout.createSequentialGroup()
                        .addGroup(ThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_maLop, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_maMon, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(ThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ThiLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(ThiLayout.createSequentialGroup()
                                .addGroup(ThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ThiLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel_ngayThi, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ThiLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel_trinhDo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(ThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ThiLayout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(jLabel8)
                                        .addContainerGap(68, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThiLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel_thoiGian)
                                        .addGap(46, 46, 46))))))
                    .addGroup(ThiLayout.createSequentialGroup()
                        .addGroup(ThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_phanchon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCauHoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(ThiLayout.createSequentialGroup()
                .addGroup(ThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThiLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel9)
                        .addGap(55, 55, 55)
                        .addComponent(jTextField_cautraloi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ThiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_NopBai)
                        .addGap(82, 82, 82)
                        .addComponent(jButton_CauTruoc)
                        .addGap(72, 72, 72)
                        .addComponent(jButton_CauSau)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ThiLayout.setVerticalGroup(
            ThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel_maMon, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ngayThi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_maLop, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_trinhDo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_thoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabelCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_phanchon, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(ThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_cautraloi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_CauTruoc)
                    .addComponent(jButton_CauSau)
                    .addComponent(jButton_NopBai))
                .addGap(73, 73, 73))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton_TaoDe.setText("Tạo đề");
        jButton_TaoDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TaoDeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("TẠO ĐỀ THI");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Chọn lịch thi");

        jTable_LichThi.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jTable_LichThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã lịch thi", "Mã môn học", "Mã lớp", "Mã giảng viên", "Ngày thi", "Thời gian", "Số câu", "Trình độ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_LichThi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_LichThiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_LichThi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(jButton_TaoDe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_TaoDe)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_TaoDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TaoDeActionPerformed
        // TODO add your handling code here:
        de.danhsachCauHoi.clear();
        dsch1mon = Modify.LayDsCauHoiCuaMon(de.maMonHoc);
        ArrayList<Integer> numbers = new ArrayList<Integer>();   
        Random random = new Random();
        while (numbers.size() < de.soCau) { // so cau hoi cua de

            int numberrandom = random .nextInt(dsch1mon.size()-1); //so cau hoi 
            if (!numbers.contains(numberrandom)) {
                numbers.add(numberrandom);
                System.out.println(numbers);
            }
        }
        
        for(Integer j: numbers)
            de.danhsachCauHoi.add(dsch1mon.get(j));
        
        
        thi(de);
        
    }//GEN-LAST:event_jButton_TaoDeActionPerformed

    private void jTable_LichThiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_LichThiMouseClicked
        // TODO add your handling code here:
        System.out.println("HELOOOOOO");
        dtm = (DefaultTableModel) jTable_LichThi.getModel();

        int j = jTable_LichThi.getSelectedRow();

        int i = jTable_LichThi.convertRowIndexToModel(j);

        de.maDT = "DT"+ (maDe++);
        de.maMonHoc = dtm.getValueAt(i, 1).toString();
        de.maLop = dtm.getValueAt(i, 2).toString();
        de.maGV = dtm.getValueAt(i, 3).toString();
        de.ngayThi = dtm.getValueAt(i, 4).toString();
        de.thoiGianThi = Integer.parseInt(dtm.getValueAt(i, 5).toString());
        de.soCau = Integer.parseInt(dtm.getValueAt(i, 6).toString());
        de.trinhDo = dtm.getValueAt(i, 7).toString();
        System.out.println("DeThi de :" + de.maDT +" | "+de.maGV+" | "+de.maLop+" | "+de.maMonHoc+" | "+de.ngayThi+" | "+de.trinhDo );
    }//GEN-LAST:event_jTable_LichThiMouseClicked

    private void jButton_NopBaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NopBaiActionPerformed
        // TODO add your handling code here:
        if(!jTextField_cautraloi.getText().equals("")){
            if(cautraloi.containsKey(n)==true) cautraloi.replace(n, jTextField_cautraloi.getText().charAt(0));
                else cautraloi.put(n, jTextField_cautraloi.getText().charAt(0));
        }
        
        
        dh.interrupt();
        JOptionPane.showMessageDialog(null, kt_dapan());
        jTextField_cautraloi.setText("");
       Thi.setVisible(false);
    }//GEN-LAST:event_jButton_NopBaiActionPerformed

    private void jButton_CauTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CauTruocActionPerformed
        // TODO add your handling code here:
        if(n>0){
            if(!jTextField_cautraloi.getText().equals("")){
                if(cautraloi.containsKey(n)==true) cautraloi.replace(n, jTextField_cautraloi.getText().charAt(0));
                else cautraloi.put(n, jTextField_cautraloi.getText().charAt(0));
                
            }
            jTextField_cautraloi.setText("");
            n--;
            hienthicauhoi(de.danhsachCauHoi.get(n));
        }
        
    }//GEN-LAST:event_jButton_CauTruocActionPerformed

    private void jButton_CauSauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CauSauActionPerformed
        // TODO add your handling code here:
        if(n<de.soCau-1){
            if(!jTextField_cautraloi.getText().equals("")){
                if(cautraloi.containsKey(n)==true) cautraloi.replace(n, jTextField_cautraloi.getText().charAt(0));
                else cautraloi.put(n, jTextField_cautraloi.getText().charAt(0));
                System.out.println(cautraloi.get(n));
            }
            jTextField_cautraloi.setText("");
            n++;
            hienthicauhoi(de.danhsachCauHoi.get(n));
        }
    }//GEN-LAST:event_jButton_CauSauActionPerformed

    private void jTextField_cautraloiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_cautraloiKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cautraloiKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThiThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThiThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThiThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThiThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new ThiThu(GiangDay giangDay, ArrayList<CauHoi> dsch).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Thi;
    private javax.swing.JButton jButton_CauSau;
    private javax.swing.JButton jButton_CauTruoc;
    private javax.swing.JButton jButton_NopBai;
    private javax.swing.JButton jButton_TaoDe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCauHoi;
    private javax.swing.JLabel jLabel_maLop;
    private javax.swing.JLabel jLabel_maMon;
    private javax.swing.JLabel jLabel_ngayThi;
    private javax.swing.JLabel jLabel_phanchon;
    private javax.swing.JLabel jLabel_thoiGian;
    private javax.swing.JLabel jLabel_trinhDo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_LichThi;
    private javax.swing.JTextField jTextField_cautraloi;
    // End of variables declaration//GEN-END:variables
}
